apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-external
data:
  EXTERNAL_SVC: "kubernetes.io"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-external
  labels:
    app: dpl-external
spec:
  selector:
    matchLabels:
      app: dpl-external
  template:
    metadata:
      labels:
        app: dpl-external
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: pod-external
        image: curlimages/curl
        command: ["sh", "-c", "while true; do echo \"[$(date)] $(curl -L -s -o /dev/null -w \"%{http_code}\n\" --connect-timeout 5 https://${EXTERNAL_SVC}/)\"; sleep 1; done;"]
        envFrom:
        - configMapRef:
            name: cfg-external
