apiVersion: v1
kind: Service
metadata:
  name: svc-external
  labels:
    service: external
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: svc-external
  labels:
    service: external-ep
subsets:
  - addresses:
      - ip: 45.54.44.102
    ports:
      - port: 443
        name: https
